spring.application.name=payroll-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/payroll
spring.datasource.username=payroll
spring.datasource.password=1818
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081
